apiVersion: v1
kind: Namespace
metadata:
  name: maxpetrikov-system
  labels:
    app.kubernetes.io/name: maxpetrikovcom-backend
    app.kubernetes.io/part-of: maxpetrikovcom
    maxpetrikov.com/scope: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: maxpetrikov-labs
  labels:
    app.kubernetes.io/name: maxpetrikov-labs
    app.kubernetes.io/part-of: maxpetrikovcom
    maxpetrikov.com/scope: lab-runtime
